### ISSUE TITLE
AzurePrivateProvider still try to create NS entries when they are not from root

### ISSUE THREAD

**Issue by benjamin-rousseau-shift** [octodns/octodns-azure#66]
In another issue I was having trouble because octosdns was saying that AzurePrivateProvider do not support root NS entries.

But with ```strict_supports``` I was able to get around that.
However when you have "delegations" in Microsoft DNS, you have NS entries for sub domains.

And when I try to sync, it tries to sync those as well (which AzurePrivateProvider can't support anyway)

here is the log : 

```
(env):~/octodns$ octodns-sync --config-file=../github/octodns/config/config.yaml --doit
2023-08-03T13:24:22  [140417629030208] INFO  Manager __init__: config_file=../github/octodns/config/config.yaml, (octoDNS 1.0.0)
2023-08-03T13:24:22  [140417629030208] INFO  Manager _config_executor: max_workers=1
2023-08-03T13:24:22  [140417629030208] INFO  Manager _config_include_meta: include_meta=False
2023-08-03T13:24:22  [140417629030208] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-08-03T13:24:22  [140417629030208] INFO  Manager __init__: global_processors=[]
2023-08-03T13:24:22  [140417629030208] INFO  Manager __init__: provider=on-premise (octodns_bind 0.0.4)
2023-08-03T13:24:22  [140417629030208] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.0.0)
2023-08-03T13:24:22  [140417629030208] INFO  Manager __init__: provider=azure (octodns_azure 0.0.5)
2023-08-03T13:24:22  [140417629030208] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False, plan_output_fh=<stdout>
2023-08-03T13:24:22  [140417629030208] INFO  Manager sync:   zone=corp.to-delete.com.
2023-08-03T13:24:22  [140417629030208] INFO  Manager sync:   sources=['on-premise'] -> targets=['azure']
2023-08-03T13:24:22  [140417629030208] INFO  AxfrSource[on-premise] populate:   found 5 records
2023-08-03T13:24:22  [140417629030208] INFO  AzurePrivateProvider[azure] plan: desired=corp.to-delete.com.
2023-08-03T13:24:23  [140417629030208] INFO  azure.identity._internal.get_token_mixin ClientSecretCredential.get_token succeeded
2023-08-03T13:24:25  [140417629030208] INFO  AzurePrivateProvider[azure] populate: found 2 records, exists=True
2023-08-03T13:24:25  [140417629030208] WARNING AzurePrivateProvider[azure] root NS record not supported for corp.to-delete.com.; ignoring it 
2023-08-03T13:24:25  [140417629030208] INFO  AzurePrivateProvider[azure] plan:   Creates=2, Updates=0, Deletes=0, Existing Records=2
2023-08-03T13:24:25  [140417629030208] INFO  Plan
********************************************************************************
* corp.to-delete.com.
********************************************************************************
* azure (AzurePrivateProvider)
*   Create <ARecord A 3600, fqdn.corp.lb.com..corp.to-delete.com., ['10.2.3.1']> ()
*   Create <NsRecord NS 0, lb.corp.to-delete.com., ['fqdn.corp.lb.com.']> ()
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=2
********************************************************************************


2023-08-03T13:24:25  [140417629030208] INFO  AzurePrivateProvider[azure] apply: making 2 changes to corp.to-delete.com.
Traceback (most recent call last):
  File "/home/windu/octodns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/manager.py", line 693, in sync
    total_changes += target.apply(plan)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/provider/base.py", line 293, in apply
    self._apply(plan)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns_azure/__init__.py", line 842, in _apply
    getattr(self, f'_apply_{class_name}')(change)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns_azure/__init__.py", line 1912, in _apply_Create
    create(
  File "/home/windu/octodns/env/lib/python3.8/site-packages/azure/mgmt/privatedns/operations/_record_sets_operations.py", line 127, in create_or_update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) The resource records' relative name 'fqdn.corp.lb.com.' must not end with a dot.       
Code: BadRequest
Message: The resource records' relative name 'fqdn.corp.lb.com.' must not end with a dot.
```

Note that there is no way in Microsoft DNS to remove the last dot for NS entries. But in any case the entry should've been ignored as they are not supported by AzurePrivateProvider

In addition it seems to be creating a 'A' record with a double dot (most likely because of the dot from the NS entry, which is kind of funny , in the UI of Microsoft DNS this entry does not even exist, but it exist in the dns file that DNS Server generate.)

Edit: It also happen when at zone level I set lenient to True

Edit 2 : 

Here is what the dnsfile look like after creating the delegation through the UI of Microsoft DNS Server : 
```
;
;  Database file corp.to-delete.com.dns for Default zone scope in zone corp.to-delete.com.
;      Zone version:  26
;

@                       IN  SOA dc.corp.to-delete.com. hostmaster.to-delete.com. (
                        		26           ; serial number
                        		900          ; refresh
                        		600          ; retry
                        		86400        ; expire
                        		3600       ) ; default TTL

;
;  Zone NS records
;

@                       NS	dc.corp.to-delete.com.

;
;  Zone records
;


;
;  Delegated sub-zone:  lb.corp.to-delete.com.
;
lb                      0	NS	fqdn.corp.lb.com.
fqdn.corp.lb.com.       A	10.2.3.1
;  End delegation

test.test               A	8.8.8.8
testi                   A	1.1.1.1
```

**Comment by benjamin-rousseau-shift** [comment]
If I manually remove the 'A' entry from the dnsfile I get this anyway : 

```
2023-08-03T13:58:29  [140135607277376] INFO  Manager __init__: config_file=../github/octodns/config/config.yaml, (octoDNS 1.0.0)
2023-08-03T13:58:29  [140135607277376] INFO  Manager _config_executor: max_workers=1
2023-08-03T13:58:29  [140135607277376] INFO  Manager _config_include_meta: include_meta=False
2023-08-03T13:58:29  [140135607277376] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-08-03T13:58:29  [140135607277376] INFO  Manager __init__: global_processors=[]
2023-08-03T13:58:29  [140135607277376] INFO  Manager __init__: provider=on-premise (octodns_bind 0.0.4)
2023-08-03T13:58:29  [140135607277376] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.0.0)
2023-08-03T13:58:29  [140135607277376] INFO  Manager __init__: provider=azure (octodns_azure 0.0.5)
2023-08-03T13:58:29  [140135607277376] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False, plan_output_fh=<stdout>
2023-08-03T13:58:29  [140135607277376] INFO  Manager sync:   zone=corp.to-delete.com.
2023-08-03T13:58:29  [140135607277376] INFO  Manager sync:   sources=['on-premise'] -> targets=['azure']
2023-08-03T13:58:29  [140135607277376] INFO  AxfrSource[on-premise] populate:   found 4 records
2023-08-03T13:58:29  [140135607277376] INFO  AzurePrivateProvider[azure] plan: desired=corp.to-delete.com.
2023-08-03T13:58:31  [140135607277376] INFO  azure.identity._internal.get_token_mixin ClientSecretCredential.get_token succeeded
2023-08-03T13:58:32  [140135607277376] INFO  AzurePrivateProvider[azure] populate: found 2 records, exists=True
2023-08-03T13:58:32  [140135607277376] WARNING AzurePrivateProvider[azure] root NS record not supported for corp.to-delete.com.; ignoring it 
2023-08-03T13:58:32  [140135607277376] INFO  AzurePrivateProvider[azure] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=2
2023-08-03T13:58:32  [140135607277376] INFO  Plan
********************************************************************************
* corp.to-delete.com.
********************************************************************************
* azure (AzurePrivateProvider)
*   Create <NsRecord NS 0, lb.corp.to-delete.com., ['fqdn.corp.lb.com.']> ()
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=2
********************************************************************************


2023-08-03T13:58:32  [140135607277376] INFO  AzurePrivateProvider[azure] apply: making 1 changes to corp.to-delete.com.
Traceback (most recent call last):
  File "/home/windu/octodns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/manager.py", line 693, in sync
    total_changes += target.apply(plan)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns/provider/base.py", line 293, in apply
    self._apply(plan)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns_azure/__init__.py", line 842, in _apply
    getattr(self, f'_apply_{class_name}')(change)
  File "/home/windu/octodns/env/lib/python3.8/site-packages/octodns_azure/__init__.py", line 1912, in _apply_Create
    create(
  File "/home/windu/octodns/env/lib/python3.8/site-packages/azure/mgmt/privatedns/operations/_record_sets_operations.py", line 127, in create_or_update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) The record type 'NS' is not supported.
Code: BadRequest
Message: The record type 'NS' is not supported.
```

**Comment by ross** [comment]
Best bet in the short term may be to use a processor to filter out the NS records completely, https://github.com/octodns/octodns/blob/6a8cf4b1e6ccc303f40803a3873b6d0f46367270/octodns/processor/filter.py#L47.

I've never personally used Azure Private DNS and I was initially surprised/disappointed that it was so different from their public DNS stuff in details/behavior. I did some quick googling trying to figure out what record types are supported by private dns and could only turn up a list for [public dns](https://learn.microsoft.com/en-us/azure/dns/dns-zones-records). 

At the very least it sounds like private DNS and public dns need to have separate supported record types rather than the existing shared set https://github.com/octodns/octodns-azure/blob/70b8c9153db8ee25e701a5b488f828560f536156/octodns_azure/__init__.py#L540-L542

No clue what's up with it not liking the dots.

**Comment by benjamin-rousseau-shift** [comment]
> Best bet in the short term may be to use a processor to filter out the NS records completely, https://github.com/octodns/octodns/blob/6a8cf4b1e6ccc303f40803a3873b6d0f46367270/octodns/processor/filter.py#L47.
> 
> I've never personally used Azure Private DNS and I was initially surprised/disappointed that it was so different from their public DNS stuff in details/behavior. I did some quick googling trying to figure out what record types are supported by private dns and could only turn up a list for [public dns](https://learn.microsoft.com/en-us/azure/dns/dns-zones-records).
> 
> At the very least it sounds like private DNS and public dns need to have separate supported record types rather than the existing shared set
> 
> https://github.com/octodns/octodns-azure/blob/70b8c9153db8ee25e701a5b488f828560f536156/octodns_azure/__init__.py#L540-L542
> 
> No clue what's up with it not liking the dots.

Wow the processor thing is awesome :) I'm very new to octodns so I'm still discovering the good stuff haha.
So it solved one issue.

Now for the next one yeah I'm still left with azure not liking the last dots

``` 2023-08-03T15:38:35  [140090077730624] DEBUG azure.core.pipeline.policies.http_logging_policy Response status: 400
Response headers:
    'Cache-Control': 'private'
    'Content-Length': '114'
    'Content-Type': 'application/json; charset=utf-8'
    'X-Content-Type-Options': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-request-id': 'ceaae14c-3213-11ee-b69e-ee8d8635af14'
    'Server': 'Microsoft-IIS/10.0'
    'X-AspNet-Version': 'REDACTED'
    'X-Powered-By': 'REDACTED'
    'x-ms-ratelimit-remaining-subscription-resource-requests': '11999'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Date': 'Thu, 03 Aug 2023 15:38:34 GMT'
Traceback (most recent call last):
  File "/home/runner/.local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.8/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/home/runner/.local/lib/python3.8/site-packages/octodns/manager.py", line 693, in sync
    total_changes += target.apply(plan)
  File "/home/runner/.local/lib/python3.8/site-packages/octodns/provider/base.py", line 293, in apply
    self._apply(plan)
  File "/home/runner/.local/lib/python3.8/site-packages/octodns_azure/__init__.py", line 842, in _apply
    getattr(self, f'_apply_{class_name}')(change)
  File "/home/runner/.local/lib/python3.8/site-packages/octodns_azure/__init__.py", line 1912, in _apply_Create
    create(
  File "/home/runner/.local/lib/python3.8/site-packages/azure/mgmt/privatedns/operations/_record_sets_operations.py", line 127, in create_or_update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) The resource records' relative name 'fqdn.corp.lb.com.' must not end with a dot.
Code: BadRequest
Message: The resource records' relative name 'fqdn.corp.lb.com.' must not end with a dot.
```

interestingly through Azure Portal, if you try to create an entry ending with a dot, it trims it for you.
Through azure cli you get the same error as through octodns (which is using azure api) : 
```Operation failed with status: 'Bad Request'. Details: The resource records' relative name 'fqdn.test.com.' must not end with a dot.```

**Comment by benjamin-rousseau-shift** [comment]
I also noticed another "issue", but not related to the above. (But I'm not sure if it's an issue for octodns or azure in that case.)

When you have more than 20 IP entries on one A entry, Azure throw an error because it can't support more than 20.
- Either octodns should do a best effort and take the 20 first while throwing a warning for the rest ?
- Azure should lift the limit lol ( I actually already opened a support ticket to see if that's something feasible but I very doubt it)

**Comment by ross** [comment]
> Now for the next one yeah I'm still left with azure not liking the last dot.

That must be something specific to private, or at least I don't know how people wouldn't have run into it with public before, azure private dns doesn't seem to be as commonly used.

> When you have more than 20 IP entries on one A entry, Azure throw an error because it can't support more than 20.

That'd definitely be an azure thing. Looks like that limit is at least documented, https://learn.microsoft.com/en-us/azure/dns/dns-zones-records#limits. Appears to apply to both public and private.

> * Either octodns should do a best effort and take the 20 first while throwing a warning for the rest ?

There's probably a lot of edge cases like it that no one has run into before. The providers can throw a SupportsException for things like that and optionally truncate the list of answers, but doing all of that (for all the situations) isn't trivial.

These two things are probably separate issues from the NS stuff, so best to file them, copying relevant info from here, into them so that they can be tracked independently.
